const info = [
  {
    memberID: 1,
    img: "https://pal4real.files.wordpress.com/2021/08/flag_of_taliban.jpg?w=1181",
    name: "Amrullah Saleh",
    designation: "Acting President",
    Country: "Afghanistan",
    City: "Kabul",
    proposedFund: 150000,
  },
  {
    memberID: 2,
    img: "https://rsf.org/sites/default/files/sheikh_hasina.png",
    name: "Sheikh Hasina",
    designation: "Prime Minister",
    Country: "Bangladesh",
    City: "Dhaka",
    proposedFund: 2000000,
  },
  {
    memberID: 3,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlgqrSZ5sgBnVQfYHXMJurOhwB6cikaHcgz8sEGis7aLz74NxRyeG5GO9adcQ_CcIAPZo&usqp=CAU",
    name: "Lotay Tshering",
    designation: "Prime Minister",
    Country: "Bhutan",
    City: "Thimphu",
    proposedFund: 1000000,
  },
  {
    memberID: 4,
    img: "https://yt3.ggpht.com/ytc/AKedOLRL4TDvw0IOANXtLLO4_aw-gWZRE_i_ATWZq7FZniM=s900-c-k-c0x00ffffff-no-rj",
    name: "Narendra Modi",
    designation: "Prime Minister",
    Country: "India",
    City: "Mumbai",
    proposedFund: 3000000,
  },

  {
    memberID: 5,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/76/Ibrahim_Mohamed_Solih_official_portrait.jpg/403px-Ibrahim_Mohamed_Solih_official_portrait.jpg",
    name: "Ibrahim Mohammad Saleh",
    designation: "President",
    Country: "Maldives",
    City: "Male",
    proposedFund: 50000,
  },
  {
    memberID: 6,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/The_former_Prime_Minister_of_Nepal%2C_Mr._Sher_Bahadur_Deuba_meeting_the_Union_Minister_for_Commerce_%26_Industry_and_Textiles%2C_Shri_Anand_Sharma%2C_in_New_Delhi_on_June_13%2C_2013_%28cropped%29.jpg/355px-thumbnail.jpg",
    name: "Sher Bahadur Deuba",
    designation: "Prime Minister",
    Country: "Nepal",
    City: "kathmondu",
    proposedFund: 250000,
  },
  {
    memberID: 7,
    img: "https://en.wikipedia.org/wiki/Imran_Khan#/media/File:Imran_Ahmed_Khan_Niazi_-_UNGA_(48784380531)_(cropped).jpg",
    name: " Imran Khan",
    designation: "Prime Minister",
    Country: "Pakistan",
    City: "Islmabad",
    proposedFund: 2500000,
  },
  {
    memberID: 8,
    img: "https://upload.wikimedia.org/wikipedia/commons/d/d0/Nandasena_Gotabaya_Rajapaksa.jpg",
    name: " Gotabaya Rajapaksa",
    designation: "President",
    Country: "Sri lanka",
    City: "Sri Jayawardenepura Kotte",
    proposedFund: 1500000,
  },
];
